### PR TITLE
Added new instances

### PR DESCRIPTION
**Pull request by SeppiaBrilla**
I have started adding the instances from the repository cited in issue #5. The port is not complete (yet)  but I'm still opening a pull request to discuss a couple of things:
- Should I include the model for bin packing to solve issue #6?
- The model of knapsack from Athanor differs a bit from the one present in the catalogue. I have copied it in the repo so that we can easily see the difference. The one from Athanor uses ```given numberItems : int(1..)``` while the one in the catalogue uses ```given items new type enum```. Which one should we keep?

### CODE REVIEW

**Comment by ndangtt** [comment]
I can answer the question about knapsack model. There are two types of knapsack instances in the repo:
- `normal-size`
- `large-size`
the normal-size ones use the `given items new type enum` model, while the large-size ones use the `given numberItems : int(1..)` model. I think performance-wise the two models should be identical. But we haven't check that empirically.

If we must use a single Essence model for all instances, we would need to modify one of the two instance sets to make sure they are compatible.

**Comment by ozgurakgun** [comment]
The two models must be identical in terms of performance since Conjure just replaces enums with ints during compilation.

What's the grading of these instances @ndangtt?

**Comment by ndangtt** [comment]
I think we should use the `given numberItems : int(1..)` model then. The other one makes the large instances extremely heavy (as the number of items is huge). Having said that, the normal-size param files need to be updated to be compatible with the chosen model (removing the `enum` bits and add a `letting numberItems be ...` ).

@ozgurakgun: those instances are fairly difficult I'd say. The large-size ones are especially challenging. We didn't measure the runtime to solve to optimality on all instances. What we did was recording the best found solution after 10 minutes and use that to compare among solvers (in addition to the intermediate solutions). If your dashboard only records the amount of time the instances are solved to optimality, my guess is that lots of those instances will produce timeout, especially the large-size ones.

**Comment by SeppiaBrilla** [comment]
Ok, the model with ```given numberItems : int(1..)``` is the one from Athanor, should I delete the one in the Catalog then?

**Comment by ozgurakgun** [comment]
hi @SeppiaBrilla - yes the int model is better. We need to update the instances then, can you do this or should one of us have a look?

also: it would be easier to manage this process if you did a PR per problem class.

**Comment by SeppiaBrilla** [comment]
Sure, I can do it! @ozgurakgun

**Comment by SeppiaBrilla** [comment]
I'll now close this pull request and delete my branch to start over with a pull request for each problem class

**Pull request closed without merging**
