### PR TITLE
added script for number of variables

### PR DESCRIPTION
**Pull request by SeppiaBrilla**
Hi, I made a new script that, creates a JSON with the number of available instances for each problem in the Catalog

### CODE REVIEW

**Comment by SeppiaBrilla** [comment]
I have also added another script that orders the problems in terms of the number of instances available

**Comment by ozgurakgun** [comment]
I see the jsons, but not a single table. Should we create one as a csv and save to the repo? Github will render it nicely if the extension is csv.

**Comment by ozgurakgun** [comment]
also I am not sure about keeping the individual json files, what we want is the aggreagate view I'd say.

**Comment by SeppiaBrilla** [comment]
sure, makes sense! I have updated the script to do just that. Now is enough to run the ```summary``` script with the problems directory as a parameter and it will print each model with its corresponding number of instances ordered in descending order. It will also create a csv file from that data

**Comment by ozgurakgun** [comment]
ha! carseq has the most instances then. good one to start with :)

**Pull request merged**
